export const personas = {
  user_personas: [
    {
      user_id: "USER001",
      name: "Alice",
      age: 30,
      gender: "Female",
      occupation: "Software Engineer",
      location: "New York, NY",
    },
    {
      user_id: "USER002",
      name: "Bob",
      age: 28,
      gender: "Male",
      occupation: "Teacher",
      location: "Los Angeles, CA",
    },
    {
      user_id: "USER003",
      name: "Charlie",
      age: 35,
      gender: "Male",
      occupation: "Doctor",
      location: "Chicago, IL",
    },
    {
      user_id: "USER004",
      name: "Vasco",
      age: 35,
      gender: "Male",
      occupation: "Extraction Manager",
      location: "Chicago, IL",
    },
    {
      user_id: "USER005",
      name: "Pascoe",
      age: 35,
      gender: "Male",
      occupation: "Former Child",
      location: "Chicago, IL",
    },
    {
      user_id: "USER006",
      name: "Sarah",
      age: 35,
      gender: "Male",
      occupation: "Doctor",
      location: "Chicago, IL",
    },
    {
      user_id: "USER007",
      name: "Mitchell",
      age: 35,
      gender: "Male",
      occupation: "Comedian",
      location: "Chicago, IL",
    },
    {
      user_id: "USER008",
      name: "David",
      age: 35,
      gender: "Male",
      occupation: "Doctor",
      location: "Chicago, IL",
    },
    {
      user_id: "USER009",
      name: "Lee",
      age: 35,
      gender: "Male",
      occupation: "Comedian",
      location: "Chicago, IL",
    },
    {
      user_id: "USER010",
      name: "Mack",
      age: 35,
      gender: "Male",
      occupation: "Doctor",
      location: "Chicago, IL",
    },
  ],
};
