export const productData = {
  appliances: [
    {
      product_id: "APP1001",
      title: "Stainless Steel Refrigerator",
      description:
        "A spacious and energy-efficient refrigerator for your kitchen.",
      price: 799.99,
      category: "Kitchen Appliances",
      average_rating: 4.5,
      image:
        "https://images.unsplash.com/photo-1610733374054-59454fe657cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    },
    {
      product_id: "APP1002",
      title: "Front-Load Washing Machine",
      description: "An advanced washing machine with multiple wash cycles.",
      price: 699.99,
      category: "Laundry Appliances",
      average_rating: 4.2,
      image:
        "https://media.istockphoto.com/id/951315880/vector/vector-realistic-front-load-washer-and-dryer.jpg?s=1024x1024&w=is&k=20&c=TtLlXx8Ch2cYrFohiQp0g1OgSvMAeHpyJmzOTOHOA8w=",
    },
    {
      product_id: "APP1003",
      title: "Microwave Oven",
      description: "A compact microwave oven with quick cooking options.",
      price: 129.99,
      category: "Kitchen Appliances",
      average_rating: 4.0,
      image:
        "https://media.istockphoto.com/id/1406993092/photo/a-cropped-photo-of-an-anonymous-caucasian-female-heating-food-in-the-oven.jpg?s=612x612&w=0&k=20&c=ddWTvEzC14kEI8WOmcc1dPR1nLThyr-H1wM_qf35OQI=",
    },
    {
      product_id: "APP1004",
      title: "Robot Vacuum Cleaner",
      description:
        "A smart vacuum cleaner that cleans your floors automatically.",
      price: 249.99,
      category: "Home Appliances",
      average_rating: 4.7,
    },
    {
      product_id: "APP1005",
      title: "Air Purifier",
      description: "A high-performance air purifier for cleaner indoor air.",
      price: 179.99,
      category: "Home Appliances",
      average_rating: 4.4,
    },
    {
      product_id: "APP1006",
      title: "Toaster Oven",
      description: "A versatile toaster oven for toasting and baking.",
      price: 69.99,
      category: "Kitchen Appliances",
      average_rating: 4.1,
    },
    {
      product_id: "APP1007",
      title: "Dishwasher",
      description: "A quiet and efficient dishwasher for hassle-free cleaning.",
      price: 549.99,
      category: "Kitchen Appliances",
      average_rating: 4.3,
    },
    {
      product_id: "APP1008",
      title: "Cordless Vacuum Cleaner",
      description:
        "A lightweight and portable vacuum cleaner for quick cleanups.",
      price: 149.99,
      category: "Home Appliances",
      average_rating: 4.6,
    },
    {
      product_id: "APP1009",
      title: "Coffee Maker",
      description:
        "A programmable coffee maker for brewing your favorite coffee.",
      price: 89.99,
      category: "Kitchen Appliances",
      average_rating: 4.0,
    },
    {
      product_id: "APP1010",
      title: "Blender",
      description: "A powerful blender for making smoothies and shakes.",
      price: 129.99,
      category: "Kitchen Appliances",
      average_rating: 4.2,
    },
    {
      product_id: "APP1011",
      title: "Electric Kettle",
      description: "A fast-boiling electric kettle for tea and hot beverages.",
      price: 34.99,
      category: "Kitchen Appliances",
      average_rating: 4.7,
    },
    {
      product_id: "APP1012",
      title: "Toaster",
      description: "A classic toaster for perfectly toasted bread slices.",
      price: 29.99,
      category: "Kitchen Appliances",
      average_rating: 4.2,
    },
    {
      product_id: "APP1013",
      title: "Food Processor",
      description: "A versatile food processor for chopping and blending.",
      price: 139.99,
      category: "Kitchen Appliances",
      average_rating: 4.5,
    },
    {
      product_id: "APP1014",
      title: "Stand Mixer",
      description: "A powerful stand mixer for baking and mixing tasks.",
      price: 199.99,
      category: "Kitchen Appliances",
      average_rating: 4.8,
    },
    {
      product_id: "APP1015",
      title: "Window Air Conditioner",
      description: "A compact window air conditioner for cooling small rooms.",
      price: 299.99,
      category: "Home Appliances",
      average_rating: 4.3,
    },
    {
      product_id: "APP1016",
      title: "Vacuum Sealer",
      description: "A vacuum sealer for preserving food freshness.",
      price: 79.99,
      category: "Kitchen Appliances",
      average_rating: 4.0,
    },
    {
      product_id: "APP1017",
      title: "Rice Cooker",
      description: "A rice cooker for perfect rice every time.",
      price: 49.99,
      category: "Kitchen Appliances",
      average_rating: 4.3,
    },
    {
      product_id: "APP1018",
      title: "Countertop Blender",
      description: "A compact countertop blender for small kitchens.",
      price: 59.99,
      category: "Kitchen Appliances",
      average_rating: 4.1,
    },
    {
      product_id: "APP1019",
      title: "Slow Cooker",
      description: "A programmable slow cooker for convenient cooking.",
      price: 79.99,
      category: "Kitchen Appliances",
      average_rating: 4.6,
    },
    {
      product_id: "APP1020",
      title: "Steam Iron",
      description: "A powerful steam iron for wrinkle-free clothes.",
      price: 39.99,
      category: "Home Appliances",
      average_rating: 4.2,
    },
    {
      product_id: "APP1021",
      title: "Portable Air Conditioner",
      description: "A portable air conditioner for cooling any room.",
      price: 349.99,
      category: "Home Appliances",
      average_rating: 4.4,
    },
    {
      product_id: "APP1022",
      title: "Handheld Vacuum Cleaner",
      description: "A handheld vacuum cleaner for quick and easy cleaning.",
      price: 49.99,
      category: "Home Appliances",
      average_rating: 4.0,
    },
    {
      product_id: "APP1023",
      title: "Dehumidifier",
      description:
        "An efficient dehumidifier for maintaining ideal humidity levels.",
      price: 199.99,
      category: "Home Appliances",
      average_rating: 4.5,
    },
    {
      product_id: "APP1024",
      title: "Espresso Machine",
      description: "A high-quality espresso machine for coffee lovers.",
      price: 299.99,
      category: "Kitchen Appliances",
      average_rating: 4.7,
    },
    {
      product_id: "APP1025",
      title: "Cordless Electric Kettle",
      description: "A cordless electric kettle for hassle-free boiling.",
      price: 44.99,
      category: "Kitchen Appliances",
      average_rating: 4.2,
    },
    {
      product_id: "APP1026",
      title: "Bread Maker",
      description: "A bread maker for fresh homemade bread.",
      price: 89.99,
      category: "Kitchen Appliances",
      average_rating: 4.3,
    },
    {
      product_id: "APP1027",
      title: "Hand Blender",
      description: "A versatile hand blender for soups and smoothies.",
      price: 34.99,
      category: "Kitchen Appliances",
      average_rating: 4.1,
    },
    {
      product_id: "APP1028",
      title: "Electric Griddle",
      description: "A large electric griddle for cooking pancakes and more.",
      price: 59.99,
      category: "Kitchen Appliances",
      average_rating: 4.5,
    },
    {
      product_id: "APP1029",
      title: "Window Fan",
      description: "A window fan for enhanced ventilation in your home.",
      price: 29.99,
      category: "Home Appliances",
      average_rating: 4.0,
    },
    {
      product_id: "APP1030",
      title: "Deep Fryer",
      description: "A deep fryer for crispy and delicious fried foods.",
      price: 49.99,
      category: "Kitchen Appliances",
      average_rating: 4.2,
    },
    {
      product_id: "APP1031",
      title: "Portable Induction Cooktop",
      description: "A portable induction cooktop for cooking on the go.",
      price: 79.99,
      category: "Kitchen Appliances",
      average_rating: 4.6,
    },
    {
      product_id: "APP1032",
      title: "Handheld Steam Cleaner",
      description: "A handheld steam cleaner for deep cleaning tasks.",
      price: 49.99,
      category: "Home Appliances",
      average_rating: 4.3,
    },
    {
      product_id: "APP1033",
      title: "Chest Freezer",
      description: "A spacious chest freezer for storing frozen goods.",
      price: 349.99,
      category: "Home Appliances",
      average_rating: 4.4,
    },
    {
      product_id: "APP1034",
      title: "Electric Can Opener",
      description: "An electric can opener for effortless can opening.",
      price: 24.99,
      category: "Kitchen Appliances",
      average_rating: 4.1,
    },
    {
      product_id: "APP1035",
      title: "Milk Frother",
      description: "A milk frother for perfect lattes and cappuccinos.",
      price: 19.99,
      category: "Kitchen Appliances",
      average_rating: 4.7,
    },
    {
      product_id: "APP1036",
      title: "Ice Maker",
      description: "A countertop ice maker for making ice cubes in minutes.",
      price: 129.99,
      category: "Kitchen Appliances",
      average_rating: 4.2,
    },
    {
      product_id: "APP1037",
      title: "Electric Wok",
      description: "An electric wok for stir-frying and cooking Asian dishes.",
      price: 49.99,
      category: "Kitchen Appliances",
      average_rating: 4.3,
    },
    {
      product_id: "APP1038",
      title: "Mini Fridge",
      description: "A compact mini fridge for dorm rooms and small spaces.",
      price: 149.99,
      category: "Kitchen Appliances",
      average_rating: 4.6,
    },
    {
      product_id: "APP1039",
      title: "Food Dehydrator",
      description: "A food dehydrator for making dried fruits and snacks.",
      price: 69.99,
      category: "Kitchen Appliances",
      average_rating: 4.4,
    },
    {
      product_id: "APP1040",
      title: "Electric Grill",
      description: "An electric grill for indoor barbecues and grilling.",
      price: 79.99,
      category: "Kitchen Appliances",
      average_rating: 4.0,
    },
    {
      product_id: "APP1041",
      title: "Juice Extractor",
      description: "A juice extractor for fresh and healthy juices.",
      price: 89.99,
      category: "Kitchen Appliances",
      average_rating: 4.2,
    },
    {
      product_id: "APP1042",
      title: "Portable Heater",
      description: "A portable heater for staying warm during the winter.",
      price: 49.99,
      category: "Home Appliances",
      average_rating: 4.5,
    },
    {
      product_id: "APP1043",
      title: "Cordless Electric Sweeper",
      description: "A cordless electric sweeper for quick cleanups.",
      price: 39.99,
      category: "Home Appliances",
      average_rating: 4.3,
    },
    {
      product_id: "APP1044",
      title: "Electric Tea Kettle",
      description: "An electric tea kettle for brewing tea with ease.",
      price: 29.99,
      category: "Kitchen Appliances",
      average_rating: 4.0,
    },
    {
      product_id: "APP1045",
      title: "Handheld Fan",
      description: "A portable handheld fan for staying cool on hot days.",
      price: 19.99,
      category: "Home Appliances",
      average_rating: 4.1,
    },
    {
      product_id: "APP1046",
      title: "Waffle Maker",
      description: "A waffle maker for delicious homemade waffles.",
      price: 39.99,
      category: "Kitchen Appliances",
      average_rating: 4.4,
    },
    {
      product_id: "APP1047",
      title: "Handheld Clothes Steamer",
      description: "A handheld clothes steamer for wrinkle-free clothes.",
      price: 24.99,
      category: "Home Appliances",
      average_rating: 4.2,
    },
    {
      product_id: "APP1048",
      title: "Electric Toothbrush",
      description: "An electric toothbrush for superior dental care.",
      price: 49.99,
      category: "Home Appliances",
      average_rating: 4.7,
    },
    {
      product_id: "APP1049",
      title: "Electric Blanket",
      description: "An electric blanket for cozy nights and warmth.",
      price: 59.99,
      category: "Home Appliances",
      average_rating: 4.0,
    },
    {
      product_id: "APP1050",
      title: "Deep Cleaning Carpet Cleaner",
      description: "A deep cleaning carpet cleaner for fresh carpets.",
      price: 179.99,
      category: "Home Appliances",
      average_rating: 4.5,
    },
  ],
};
